In [2]:
my_list = [1,2,3]

In [5]:
import numpy as np

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [8]:
my_list2 = [[1,2],[3,4]]

In [9]:
np.array(my_list2)

array([[1, 2],
       [3, 4]])

In [10]:
np.arange(2,10,3)

array([2, 5, 8])

In [11]:
np.linspace(0,10,10)

array([  0.        ,   1.11111111,   2.22222222,   3.33333333,
         4.44444444,   5.55555556,   6.66666667,   7.77777778,
         8.88888889,  10.        ])

In [12]:
np.random.rand(5,5)

array([[ 0.23263396,  0.28961084,  0.28135795,  0.61305902,  0.8473397 ],
       [ 0.36502906,  0.35546405,  0.33255419,  0.92988771,  0.93741918],
       [ 0.7460097 ,  0.14544571,  0.60556431,  0.60651604,  0.95801316],
       [ 0.99245427,  0.57172442,  0.69410475,  0.24858636,  0.01268241],
       [ 0.67408594,  0.1781634 ,  0.13850773,  0.08973845,  0.36731563]])

In [13]:
np.random.randint(1,100,10)

array([40, 12, 25, 81, 39, 94, 34, 19, 71, 32])

In [15]:
np.linspace(0,10,10).dtype()

TypeError: 'numpy.dtype' object is not callable

In [16]:
np.linspace(0,10,10).dtype()

TypeError: 'numpy.dtype' object is not callable

In [17]:
arr = np.linspace(0,10,10)

In [18]:
arr

array([  0.        ,   1.11111111,   2.22222222,   3.33333333,
         4.44444444,   5.55555556,   6.66666667,   7.77777778,
         8.88888889,  10.        ])

In [20]:
arr.dtype()

TypeError: 'numpy.dtype' object is not callable

In [26]:
arr = np.arange(1,11)

In [27]:
arr[arr>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [22]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr[arr>3]

TypeError: 'int' object is not subscriptable

In [24]:
arr

99

In [28]:
arr_2w = np.arange(50).reshape(5,10)

In [29]:
arr_slice = arr_2w[1:3,4:6]

In [30]:
arr_slice

array([[14, 15],
       [24, 25]])